### ISSUE TITLE
Please update your modules

### ISSUE THREAD

**Issue by Munsio** [hauptstadtcode/hc_mailchimp#2]
Hey there,

Please update your source code cause the module code doesn't follow the contao guidelines.

here are some examples:

```
$moduleParams = Database::getInstance()
            ->prepare("SELECT * FROM tl_module WHERE id=?")
            ->limit(1)
            ->execute($this->id);

        // id der angelegten Liste im Backend Mailchimp
$listid = $moduleParams->hc_mailchimp_unsubscribeForm_mailchimplist;
```

You do not need any database access in here cause you can access "hc_mailchimp_unsubscribeForm_mailchimplist" with the $this parameter "$this->hc_mailchimp_unsubscribeForm_mailchimplist" this is for all module attributes.

Do not use $_POST use \Input::post('key') - if you do so you got contaos internal strip/specialchar/trim functions called automatically, so you also don't need to use functions like your "daten_reiniger"

Usage of many errorCode if statements.
You should use an switch() block or an lang array for the errorCode and pass the error string to 1 error var.

```
if($api->errorCode){
$this->Template->error = $GLOBALS['TL_LANG']['hc_mailchimp'][$api->errorCode]
}else{
$this->Template->error = NULL;
}
```

Use an additional hidden value parameter to detect if the form is an subscribe/unsubscribe, with this it is possible to use both forms on the same site

There are a lot more like:

```
if($moduleParams->hc_mailchimp_optin_mailchimplist){
                // User in Liste aufnehmen bzw- Opt-In Verfahren starten
                $api->listSubscribe( $mailchimpObject->listid, $_POST['EMAIL'], $_POST, 'html' );
            } else {
                // User in Liste aufnehmen ohne Opt-In Verfahren
                $api->listSubscribe( $mailchimpObject->listid, $_POST['EMAIL'], $_POST, 'html', false );
            }
```

Where you can pass the last boolean without the if statement.
It would make your code smaller and better readable.

EDIT:
The Contao Input Class doesn't give you a feature to get all POST keys but with following foreach it is possible:

```
$values = array();
foreach(array_keys($_POST) as $key) {
        $values[$key] = \Input::post($key);
}
```

**Comment by hauptstadtcode** [comment]
Ok. The code has refactor. I hope now it is better for coding guidelines.
